name: Run Pytest Tests

on: [push, pull_request]  # Trigger the workflow on push and pull request events

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the Python version to be used

    - name: Install dependencies
      run: pip install -r requirements.txt  # Install the dependencies listed in requirements.txt file

    - name: Install Chrome
      run: sudo apt-get update && sudo apt-get install -y google-chrome-stable  # Install Chrome browser

    - name: Install Chromedriver
      run: sudo apt-get install -y chromium-chromedriver  # Install Chromedriver

    - name: Run Pytest
      run: pytest test.py  # Run Pytest with Chrome driver
