name: Python Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install selenium
        
    - name: Download Chrome driver
      run: |
        CHROME_DRIVER_VERSION=94.0.4606.41
        wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P $HOME
        unzip $HOME/chromedriver_linux64.zip -d $HOME
        
    - name: Start Google Chrome
      run: google-chrome-stable &
      
    - name: Run tests with Chrome in headless mode
      run: |
        google-chrome-stable --headless --disable-gpu --disable-gpu-sandbox --remote-debugging-port=9222 &
        python -m pytest --driver Chrome --driver-path $HOME/chromedriver

